version: "3.7"

services:
  backend:
    build: ./backend/.
    container_name: backend
    restart: unless-stopped
    ports:
      - "${PORT_BACKEND}:${PORT_BACKEND}"
    volumes:
      - pocketbase-data:/dist/pb_data
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:${PORT}/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  frontend:
    build: ./frontend/.
    container_name: frontend
    restart: unless-stopped
    ports:
      - "${PORT_FRONTEND}:${PORT_FRONTEND}"
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:${PORT_FRONTEND}/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

volumes:
  pocketbase-data:
