version: "3.7"

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - pocketbase-data:/pb_data
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:${PORT}/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

volumes:
  pocketbase-data:
